### ISSUE TITLE
zookeeper-client method issue

### ISSUE THREAD

**Issue by aliartiza75** [alexguan/node-zookeeper-client#69]
Hello everyone,
The code given below connects to zookeeper. But the issue is that if the connection is unsuccessful then the code stucks. Is there a way to check weather connection successful or not
                       
 
                  var zookeeper = require('node-zookeeper-client'); 
                  var client = zookeeper.createClient("localhost:2182", { sessionTimeout: 1000, retries: 0 });
                  let timeoutTimeperiod = 10000 
                  client.connect();

Code stucks in the codes below:
                 
                   client.setData(path, buffer, defaultVersion, function (error, stat) {
			// failure
			if (error) {
				client.close();
				response['message'] = 'Failed to set data on node : ' + path;
				response['path'] = path;
				response['error'] = error;
				reject(response);
			}
			// success
			client.close();
			response['message'] = 'Data has been set on node : ' + path;
			response['error'] = 'NIL';
			response['status'] = true;
			resolve(response);
		  });

Need help, thanks in advance

**Comment by aliartiza75** [comment]
@alexguan kindly have a look at this issue

**Comment by aliartiza75** [comment]
@alexguan kindly have a look at this issue

**Comment by alexguan** [comment]
You need to wait for the client `connected` event before setting data: see this for an example:

https://github.com/alexguan/node-zookeeper-client/blob/master/examples/set.js
