### ISSUE TITLE
zookeeper connect not working

### ISSUE THREAD

**Issue by aliartiza75** [alexguan/node-zookeeper-client#71]
I have written a script:

          var zookeeper = require('node-zookeeper-client');
          let zk_addr = "localhost:2182" 
          var client = zookeeper.createClient(zk_addr, { sessionTimeout: 1000, retries: 0 });
          client.connect()

In this example the zookeeper address is incorrect. So the script tries to reconnect and doesn't timeout.
I want my script to timeout after some time. 

Help would be appreciated

Thanks

**Comment by immatt2015** [comment]
Same problem.

**Comment by aliartiza75** [comment]
I have currently used the js timeout utility to exit this condition.

**Comment by aliartiza75** [comment]
@alexguan kindly have a look at this issue

**Comment by aliartiza75** [comment]
@alexguan kindly have a look at this issue

**Comment by aliartiza75** [comment]
this problem has been resolved in this [issue](https://github.com/alexguan/node-zookeeper-client/issues/69)
