### ISSUE TITLE
结点添加不上

### ISSUE THREAD

**Issue by taoqf** [alexguan/node-zookeeper-client#81]
英文水平太次，担心英语描述不清楚，用国语吧。
我的使用情况是这样的，服务启动的时候会向zookeeper里添加一个结点，很普通很平常的一个结点。然后我服务里又启动了一个另外一个服务的监听。当某种异常情况我另外那个监听服务的连接会失败，这个时候我要自动重启监听，而同时呢，我会再次添加向zookeeper中添加结点，就在这个时候（看服务日志是这个时候），结点添加不上，从zkui中看不到结点，但是代码中并没有报创建结点失败的错误。
因为这种情况不容易重现，目前也没有找到办法模拟，但是这个问题确实出现过几次。现在我分析不出来原因了，希望各位老大帮帮忙，万分感激。 @alexguan

**Comment by ghostuz** [comment]
Hi @taoqf I am Chinese too. plz used english here if you really want some guys answer your question.
let me try to translate you question here. plz point me out any mistake.

reproduce steps:
1. try to create a node in zookeeper when my application startup. success.
Q: what kind node you created. CreateMode.PERSISTENT or CreateMode.EPHEMERAL. I guess is PERSISTENT node
2. add watcher for another node.
Q: watch child nodes or watch data. I mean you used getChildren for add watcher or use getData.
3. client will disconnected sometimes.
Q: the same client or not.
4. automatic restart watch? 
A: you mean watch again in client on disconnected event? plz paste code better.
5. in the restart watch logical. you try to create same node in zookeeper
7. I can not found any create node error message.

I think you better paste code here.

这里再用中文描述一下, 顺便有几个问题

@taoqf 英文很重要, 不然别人都不知道你问什么, 如何回答你哈.
我把你的描述转成了重现的步骤, 其中有几点你没哟描述清楚
1. 在程序启动时, 你会在 zookeeper 中创建一个节点, 你描述的普通节点, 我认为是持久化的节点, 这点就有点奇怪了, 如果是持久化的节点, 你应该是在程序启动时确保该节点存在, 不存在就创建.
2. 然后监听另外一个节点, 是用同一个 client 去监听, 还是每节点一个 client, 是监听的节点的值还是节点的子节点.感觉这点区别不大
3. 监听的连接会断开, 是同一个 client 断开, 还是独立的一个 client 断开, 这个就比较复杂了.
4. 自动重启监听, 应该是在 client 接收到断开事件时去重新监听和创建节点吧. 
5. 按照你说的, 如果在第一步时创建的是永久节点, 不管任何时候再去创建, 都会受到错误, 但是你没有收到, 这点就比较奇怪了, 

把代码贴出来, 不然真不知道你说的是什么

**Comment by taoqf** [comment]
Thanks very much @ghostuz .

1. I create a node in `EPHEMERAL` mode when my app startup.
1. The other listener is nothing to do with zookeeper, like httpserver.
1. httpserver shutdown because of some reasons.
1. I restart httpserver after it shut down.
1. I create another connection to zookeeper, and recreate another 'EPHEMERAL' node like I did at step 1, Then I won't get any error message after the node is created, even the node is not created correctly.
