### ISSUE TITLE
Remove use of deprecated Buffer() constructor 

### ISSUE THREAD

**Issue by ManfredLange** [alexguan/node-zookeeper-client#92]
Node 10 has deprecated the Buffer constructor 'new Buffer()` (see [Node JS Documentation](https://nodejs.org/api/buffer.html)).

While this may not affect the use of `node-zookeeper-client` within `node_modules` it becomes a problem when packaging up using webpack and then deploying to a node 10.x (or later) runtime environment, e.g. when running in the current AWS lambda node environment (nodejs 10.x).

When running in such an environment, an error message like the following will be produced:
```
ERROR	(node:7) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

In the case of AWS lambdas, this leads to non functioning lambdas as the deprecation warning is treated as an error when using nodejs 10.x as the runtime.

**Comment by alexguan** [comment]
Changing it seems reasonable, my concerns is that this will make the library requires node.js version older than 6.0.0.

Not sure how many folks has not yet upgraded.

**Comment by ManfredLange** [comment]
Fantastic! Thank you so much for the fast turn around! :-)
